import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'
import BootstrapClient from "./BootstrapClient";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <BootstrapClient/>
        {children}
      </body>
    </html>
  );
}
